### ISSUE TITLE
Tries to add subscriber from ANY form

### ISSUE THREAD

**Issue by imakeitworknet** [siterig/statamic-mailerlite#21]
Hi.
Statamic 3.4.11
Statamic Mailerlite 1.1.5

Previously had only one form in Statamic - Newsletter subscription form, and everything worked as expected.
Now added second form which has nothing to do with subscriptions, but getting error 

 **"Undefined array key "email_field"** 
 from
 **public function addSubscriber(array $config, object $submission_data)**

which should not fire on that form submission at all.

Only one (another) form is set up in Statamic's Mailerlite Settings page.
Any ideas?

**Comment by MeMattStone** [comment]
This issue is resolved in a release due next week based on changes to our other add-on [here](https://github.com/siterig/statamic-sendinblue/pull/4) which will be merged across into this add-on next week and a release published.

Apologies for the extended delay on this update.

If you have any further question please reply to this issue
